flit 3.11 does not like the License classifier
flit_core.config.ConfigError: License classifiers are deprecated in favor of the license expression.
                              Remove the 'License :: OSI Approved :: MIT License' classifier