Adopt PEP 639 "license" field (#914)
* PEP 639 compliance

Keep the redundant Trove classifier for now, until tools such as
pip-licenses support PEP 639.

* No need to explictly specify LICENSE file

Indeed flit will automatically pick up files with standard names,
including `LICEN[CS]E*`:
https://flit.pypa.io/en/stable/pyproject_toml.html#new-style-metadata

* Bump flit to 3.11 for basic PEP 639 support

https://flit.pypa.io/en/stable/history.html#version-3-11

* flit 3.11 does not like the License classifier

flit_core.config.ConfigError: License classifiers are deprecated in favor of the license expression.
                              Remove the 'License :: OSI Approved :: MIT License' classifier